davinci:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  one_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_yaw_joint
    pid: {p: 100.0, i: 0.5, d: 10.0}
  one_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint
    pid: {p: 50.0, i: 0.1, d: 5.0}
  one_joint2_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_1
    pid: {p: 50.0, i: 0.5, d: 5.0}
  one_joint2_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_2
    pid: {p: 50.0, i: 0.1, d: 5.0}
  one_joint2_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_3
    pid: {p: 30.0, i: 0.5, d: 2.0}
  one_joint2_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_4
    pid: {p: 30.0, i: 0.1, d: 2.0}
  one_joint2_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_pitch_joint_5
    pid: {p: 20.0, i: 0.1, d: 1.0}
  one_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_insertion_joint
    pid: {p: 1000.0, i: 0.1, d: 100.0}
  one_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_roll_joint
    pid: {p: 10.0, i: 0.1, d: 5.0} 

  one_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_pitch_joint
    pid: {p: 1.0, i: 0.1, d: 1.0} 
  one_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_yaw_joint
    pid: {p: 10.0, i: 0.1, d: 1.0} 
  one_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_open_angle_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}     
  one_joint7_position_controller_mimic:
    type: effort_controllers/JointPositionController
    joint: one_outer_wrist_open_angle_joint_mimic
    pid: {p: 10.0, i: 0.1, d: 1.0} 
    
  two_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_yaw_joint
    pid: {p: 100.0, i: 0.5, d: 10.0}
  two_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint
    pid: {p: 50.0, i: 0.1, d: 5.0}
  two_joint2_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint_1
    pid: {p: 50.0, i: 0.5, d: 5.0}
  two_joint2_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint_2
    pid: {p: 50.0, i: 0.1, d: 5.0}
  two_joint2_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint_3
    pid: {p: 30.0, i: 0.5, d: 2.0}
  two_joint2_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint_4
    pid: {p: 30.0, i: 0.1, d: 2.0}
  two_joint2_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_pitch_joint_5
    pid: {p: 20.0, i: 0.1, d: 1.0}
  two_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_insertion_joint
    pid: {p: 1000.0, i: 0.1, d: 100.0}
  two_joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_roll_joint
    pid: {p: 10.0, i: 0.1, d: 5.0}   
    
  two_joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_wrist_pitch_joint
    pid: {p: 1.0, i: 0.1, d: 1.0} 
  two_joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_wrist_yaw_joint
    pid: {p: 10.0, i: 0.1, d: 1.0} 
  two_joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: two_outer_wrist_open_angle_joint
    pid: {p: 10.0, i: 0.1, d: 1.0} 
  two_joint7_position_controller_mimic:
    type: effort_controllers/JointPositionController
    joint: two_outer_wrist_open_angle_joint_mimic
    pid: {p: 10.0, i: 0.1, d: 1.0}     